### ISSUE TITLE
In Logseq, the half-width symbols  (eg:[ ] )can affect the formatting of footnotes. 

### ISSUE THREAD

**Issue by Hyc152** [gremi-jr/logseq-footnote-plugin#2]
![录制_2024_03_05_11_17_38_974](https://github.com/gremi-jr/logseq-footnote-plugin/assets/53823339/f6b1557b-a5d1-4f4e-90e6-f02aaa137533)

**Comment by gremi-jr** [comment]
Unfortunately this is not an issue from the plugin but rather Logseq itself. Logseq does the footnote rendering/formatting, not the plugin.
